-- ============================================================
-- ランクマッチ（対人戦のレート戦） ※is_admin限定の先行実装
-- ------------------------------------------------------------
-- ・初期レート1000。変動は挑戦した側のみ＝基準15にレート差補正±5
--   （勝ち +15±5 / 負け -15±5 / 引き分け 0。防衛側＝対戦相手に選ばれた側は変動なし）
-- ・マッチング＝レート±100からランダム（未参加者はレート1000扱い）
-- ・挑戦は1時間に1回（rank_find_opponent でCD判定）
-- ・シーズン＝月次（JST・'YYYY-MM'）。終了後に最終順位に応じてGold報酬
-- ・戦闘はクライアント（simulatePvpBattle・組み手と同じHP補正なし）で実行し
--   rank_report_result で結果を確定（find時に相手を固定＝pending方式）
--
-- 適用順: protect_stats 系より後（Gold付与で app.allow_stat_change を使用）。
--         mutant_gold_20260703.sql(v2) の前後どちらでも可（apply_battle_result等は触らない）。
-- 一般公開時: 各関数の「開発限定ゲート」ブロックを削除する。
-- ============================================================

-- ① レートテーブル -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS rank_ratings (
  player_id        uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  season           text NOT NULL,                 -- 'YYYY-MM'（JST月次）
  rating           int  NOT NULL DEFAULT 1000,
  wins             int  NOT NULL DEFAULT 0,       -- 挑戦した対戦の勝敗のみ記録（防衛側は変動レートのみ）
  losses           int  NOT NULL DEFAULT 0,
  draws            int  NOT NULL DEFAULT 0,
  last_match_at    timestamptz,                   -- 挑戦CD（1時間）の基準
  pending_opponent uuid REFERENCES profiles(id) ON DELETE SET NULL,
  pending_at       timestamptz,
  reward_claimed   boolean NOT NULL DEFAULT false,
  updated_at       timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (player_id, season)
);
CREATE INDEX IF NOT EXISTS idx_rank_ratings_season_rating ON rank_ratings(season, rating DESC);

ALTER TABLE rank_ratings ENABLE ROW LEVEL SECURITY;
-- ランキング表示用に全員閲覧可（書き込みはRPCのみ）
DROP POLICY IF EXISTS rank_ratings_select_all ON rank_ratings;
CREATE POLICY rank_ratings_select_all ON rank_ratings FOR SELECT TO authenticated USING (true);

-- ② 対戦ログ -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS rank_matches (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season        text NOT NULL,
  challenger_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  opponent_id   uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  winner        text NOT NULL,            -- 'challenger' | 'opponent' | 'draw'
  rating_delta  int  NOT NULL DEFAULT 0,  -- 挑戦者のレート変動（相手は-delta）
  challenger_rating_after int NOT NULL DEFAULT 1000,
  opponent_rating_after   int NOT NULL DEFAULT 1000,
  turns         int  NOT NULL DEFAULT 0,
  a_hp_pct      real NOT NULL DEFAULT 0,
  b_hp_pct      real NOT NULL DEFAULT 0,
  created_at    timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE rank_matches ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rank_matches_select_own ON rank_matches;
CREATE POLICY rank_matches_select_own ON rank_matches
  FOR SELECT USING (auth.uid() = challenger_id OR auth.uid() = opponent_id);

-- ③ 共通ヘルパー ---------------------------------------------------------------
-- 現在シーズンキー（JST月次）
CREATE OR REPLACE FUNCTION rank_current_season()
RETURNS text LANGUAGE sql STABLE AS $$
  SELECT to_char(now() AT TIME ZONE 'Asia/Tokyo', 'YYYY-MM')
$$;

-- 順位→Gold報酬（バランスは後で調整可）
CREATE OR REPLACE FUNCTION rank_reward_for(p_rank int)
RETURNS int LANGUAGE sql IMMUTABLE AS $$
  SELECT CASE
    WHEN p_rank = 1 THEN 100000
    WHEN p_rank = 2 THEN 70000
    WHEN p_rank = 3 THEN 50000
    WHEN p_rank <= 10 THEN 30000
    WHEN p_rank <= 30 THEN 15000
    WHEN p_rank <= 100 THEN 8000
    ELSE 3000
  END
$$;

-- ④ 状態取得（自分のレート・CD・ランキング・前シーズン報酬） --------------------
CREATE OR REPLACE FUNCTION rank_get_state()
RETURNS json
LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_season      text := rank_current_season();
  v_me          rank_ratings%ROWTYPE;
  v_is_admin    boolean;
  v_cd_remain   int := 0;
  v_my_rank     int := NULL;
  v_board       json;
  v_prev        json := NULL;
  v_prev_season text;
  v_prev_row    rank_ratings%ROWTYPE;
  v_prev_rank   int;
BEGIN
  IF auth.uid() IS NULL THEN RETURN json_build_object('error', '未認証です'); END IF;
  SELECT EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND is_admin) INTO v_is_admin;
  -- ▼開発限定ゲート（一般公開時にこのブロックを削除）
  IF NOT v_is_admin THEN
    RETURN json_build_object('error', '開発中の機能です');
  END IF;
  -- ▲

  SELECT * INTO v_me FROM rank_ratings WHERE player_id = auth.uid() AND season = v_season;
  IF v_me.player_id IS NOT NULL THEN
    -- is_adminはCD免除（開発中は0秒。一般公開後も管理者はCDなしのまま＝他機能と同方針）
    IF NOT v_is_admin AND v_me.last_match_at IS NOT NULL THEN
      v_cd_remain := GREATEST(0, CEIL(EXTRACT(EPOCH FROM (v_me.last_match_at + interval '1 hour' - now())))::int);
    END IF;
    SELECT 1 + COUNT(*) INTO v_my_rank FROM rank_ratings r
      WHERE r.season = v_season AND r.rating > v_me.rating;
  END IF;

  -- ランキング上位10（集計除外アカウントは非表示。自分の順位は my_rank で別途表示）
  SELECT COALESCE(json_agg(t), '[]'::json) INTO v_board FROM (
    SELECT p.username, r.rating, r.wins, r.losses, r.draws
    FROM rank_ratings r JOIN profiles p ON p.id = r.player_id
    WHERE r.season = v_season AND COALESCE(p.exclude_from_ranking, false) = false
    ORDER BY r.rating DESC, r.updated_at ASC
    LIMIT 10
  ) t;

  -- 直近の過去シーズン（自分が参加した最新のもの）の報酬情報
  SELECT season INTO v_prev_season FROM rank_ratings
    WHERE player_id = auth.uid() AND season < v_season AND (wins + losses + draws) > 0
    ORDER BY season DESC LIMIT 1;
  IF v_prev_season IS NOT NULL THEN
    SELECT * INTO v_prev_row FROM rank_ratings WHERE player_id = auth.uid() AND season = v_prev_season;
    SELECT 1 + COUNT(*) INTO v_prev_rank FROM rank_ratings r
      WHERE r.season = v_prev_season AND r.rating > v_prev_row.rating;
    v_prev := json_build_object(
      'season', v_prev_season, 'rating', v_prev_row.rating, 'rank', v_prev_rank,
      'reward', rank_reward_for(v_prev_rank), 'claimed', v_prev_row.reward_claimed);
  END IF;

  RETURN json_build_object(
    'ok', true, 'season', v_season,
    'rating', COALESCE(v_me.rating, 1000),
    'wins', COALESCE(v_me.wins, 0), 'losses', COALESCE(v_me.losses, 0), 'draws', COALESCE(v_me.draws, 0),
    'cd_remain', v_cd_remain, 'my_rank', v_my_rank,
    'leaderboard', v_board, 'prev_season', v_prev);
END;
$$;
GRANT EXECUTE ON FUNCTION rank_get_state() TO authenticated;

-- ⑤ マッチング（レート±100からランダム・1時間CD） ------------------------------
CREATE OR REPLACE FUNCTION rank_find_opponent()
RETURNS json
LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_season    text := rank_current_season();
  v_me        rank_ratings%ROWTYPE;
  v_is_admin  boolean;
  v_opp       record;
  v_cd_remain int;
BEGIN
  IF auth.uid() IS NULL THEN RETURN json_build_object('error', '未認証です'); END IF;
  SELECT EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND is_admin) INTO v_is_admin;
  -- ▼開発限定ゲート（一般公開時にこのブロックを削除）
  IF NOT v_is_admin THEN
    RETURN json_build_object('error', '開発中の機能です');
  END IF;
  -- ▲

  -- ベータ版の開催期間: JST 2026-07-31 23:59まで（延長時はこの日時を変更）
  IF (now() AT TIME ZONE 'Asia/Tokyo') > timestamp '2026-07-31 23:59:59' THEN
    RETURN json_build_object('error', 'ベータ期間は終了しました');
  END IF;

  -- 自分の行が無ければ作成（初期レート1000）
  INSERT INTO rank_ratings(player_id, season) VALUES (auth.uid(), v_season)
    ON CONFLICT (player_id, season) DO NOTHING;
  SELECT * INTO v_me FROM rank_ratings WHERE player_id = auth.uid() AND season = v_season FOR UPDATE;

  -- 挑戦CD: 1時間に1回（is_adminは免除＝開発中は0秒。一般公開後も管理者はCDなしのまま）
  IF NOT v_is_admin AND v_me.last_match_at IS NOT NULL AND now() < v_me.last_match_at + interval '1 hour' THEN
    v_cd_remain := CEIL(EXTRACT(EPOCH FROM (v_me.last_match_at + interval '1 hour' - now())))::int;
    RETURN json_build_object('error', 'クールダウン中です', 'cd_remain', v_cd_remain);
  END IF;

  -- 未消化のマッチが直近にあればそのまま返す（リロード等での再マッチ悪用防止）
  IF v_me.pending_opponent IS NOT NULL AND v_me.pending_at > now() - interval '10 minutes' THEN
    SELECT p.id, p.username, COALESCE(p.char_lv, p.lv) AS char_lv, p.class,
           COALESCE(r.rating, 1000) AS rating
    INTO v_opp
    FROM profiles p LEFT JOIN rank_ratings r ON r.player_id = p.id AND r.season = v_season
    WHERE p.id = v_me.pending_opponent;
    IF v_opp.id IS NOT NULL THEN
      RETURN json_build_object('ok', true, 'resumed', true, 'opponent', row_to_json(v_opp), 'my_rating', v_me.rating);
    END IF;
  END IF;

  -- レート±100からランダム1名（未参加者はレート1000扱い・集計除外/自分は除く）
  SELECT p.id, p.username, COALESCE(p.char_lv, p.lv) AS char_lv, p.class,
         COALESCE(r.rating, 1000) AS rating
  INTO v_opp
  FROM profiles p LEFT JOIN rank_ratings r ON r.player_id = p.id AND r.season = v_season
  WHERE p.id <> auth.uid()
    AND COALESCE(p.exclude_from_ranking, false) = false
    AND COALESCE(r.rating, 1000) BETWEEN v_me.rating - 100 AND v_me.rating + 100
  ORDER BY random()
  LIMIT 1;

  IF v_opp.id IS NULL THEN
    RETURN json_build_object('error', format('レート±100（%s〜%s）の相手が見つかりませんでした', v_me.rating - 100, v_me.rating + 100));
  END IF;

  UPDATE rank_ratings SET pending_opponent = v_opp.id, pending_at = now(), updated_at = now()
    WHERE player_id = auth.uid() AND season = v_season;

  RETURN json_build_object('ok', true, 'opponent', row_to_json(v_opp), 'my_rating', v_me.rating);
END;
$$;
GRANT EXECUTE ON FUNCTION rank_find_opponent() TO authenticated;

-- ⑥ 結果確定（レート変動＋CD起点セット） ----------------------------------------
--    変動は挑戦した側のみ（対戦相手に選ばれた側＝防衛側は変動なし）。
--    変動量: 基準15にレート差補正±5（相手が格上なら勝ち増・負け減、格下なら逆）。
--      補正 = clamp(round((相手レート - 自分レート) / 20), -5, +5)  ※±100マッチなのでちょうど±5
--      勝ち: +(15 + 補正) / 負け: -(15 - 補正) / 引き分け: 0
CREATE OR REPLACE FUNCTION rank_report_result(
  p_winner   text,   -- 'challenger' | 'opponent' | 'draw'
  p_turns    int,
  p_a_hp_pct real,
  p_b_hp_pct real
) RETURNS json
LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_season  text := rank_current_season();
  v_me      rank_ratings%ROWTYPE;
  v_opp_id  uuid;
  v_opp_r   int;
  v_adj     int;
  v_delta   int;
  v_new_me  int;
BEGIN
  IF auth.uid() IS NULL THEN RETURN json_build_object('error', '未認証です'); END IF;
  -- ▼開発限定ゲート（一般公開時にこのブロックを削除）
  IF NOT EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND is_admin) THEN
    RETURN json_build_object('error', '開発中の機能です');
  END IF;
  -- ▲
  IF p_winner NOT IN ('challenger', 'opponent', 'draw') THEN
    RETURN json_build_object('error', 'winner不正');
  END IF;

  SELECT * INTO v_me FROM rank_ratings WHERE player_id = auth.uid() AND season = v_season FOR UPDATE;
  IF v_me.player_id IS NULL OR v_me.pending_opponent IS NULL THEN
    RETURN json_build_object('error', 'マッチング中の対戦がありません');
  END IF;
  IF v_me.pending_at < now() - interval '10 minutes' THEN
    UPDATE rank_ratings SET pending_opponent = NULL, pending_at = NULL WHERE player_id = auth.uid() AND season = v_season;
    RETURN json_build_object('error', 'マッチングの有効期限が切れました。再マッチしてください');
  END IF;
  v_opp_id := v_me.pending_opponent;

  -- 相手の現在レート（未参加なら1000扱い。防衛側のレートは変動させない＝読むだけ）
  SELECT COALESCE((SELECT rating FROM rank_ratings WHERE player_id = v_opp_id AND season = v_season), 1000)
    INTO v_opp_r;

  -- 変動量: 基準15＋レート差補正（±5）。挑戦側のみ変動
  v_adj   := LEAST(5, GREATEST(-5, round((v_opp_r - v_me.rating) / 20.0)::int));
  v_delta := CASE p_winner
    WHEN 'challenger' THEN 15 + v_adj
    WHEN 'opponent'   THEN -(15 - v_adj)
    ELSE 0
  END;
  v_new_me := v_me.rating + v_delta;

  UPDATE rank_ratings SET
    rating = v_new_me,
    wins   = wins   + CASE WHEN p_winner = 'challenger' THEN 1 ELSE 0 END,
    losses = losses + CASE WHEN p_winner = 'opponent'   THEN 1 ELSE 0 END,
    draws  = draws  + CASE WHEN p_winner = 'draw'       THEN 1 ELSE 0 END,
    last_match_at = now(), pending_opponent = NULL, pending_at = NULL, updated_at = now()
    WHERE player_id = auth.uid() AND season = v_season;

  INSERT INTO rank_matches(season, challenger_id, opponent_id, winner, rating_delta,
                           challenger_rating_after, opponent_rating_after, turns, a_hp_pct, b_hp_pct)
  VALUES (v_season, auth.uid(), v_opp_id, p_winner, v_delta, v_new_me, v_opp_r,
          COALESCE(p_turns, 0), COALESCE(p_a_hp_pct, 0), COALESCE(p_b_hp_pct, 0));

  RETURN json_build_object('ok', true, 'delta', v_delta, 'new_rating', v_new_me, 'cd_remain', 3600);
END;
$$;
GRANT EXECUTE ON FUNCTION rank_report_result(text, int, real, real) TO authenticated;

-- ⑦ シーズン報酬受け取り（過去シーズンの最終順位に応じてGold） ------------------
CREATE OR REPLACE FUNCTION rank_claim_season_reward(p_season text)
RETURNS json
LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_row    rank_ratings%ROWTYPE;
  v_rank   int;
  v_reward int;
BEGIN
  IF auth.uid() IS NULL THEN RETURN json_build_object('error', '未認証です'); END IF;
  -- ▼開発限定ゲート（一般公開時にこのブロックを削除）
  IF NOT EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND is_admin) THEN
    RETURN json_build_object('error', '開発中の機能です');
  END IF;
  -- ▲
  IF p_season IS NULL OR p_season >= rank_current_season() THEN
    RETURN json_build_object('error', 'シーズン終了後に受け取れます');
  END IF;

  SELECT * INTO v_row FROM rank_ratings WHERE player_id = auth.uid() AND season = p_season FOR UPDATE;
  IF v_row.player_id IS NULL OR (v_row.wins + v_row.losses + v_row.draws) = 0 THEN
    RETURN json_build_object('error', 'このシーズンの対戦記録がありません');
  END IF;
  IF v_row.reward_claimed THEN
    RETURN json_build_object('error', '受け取り済みです');
  END IF;

  SELECT 1 + COUNT(*) INTO v_rank FROM rank_ratings r
    WHERE r.season = p_season AND r.rating > v_row.rating;
  v_reward := rank_reward_for(v_rank);

  PERFORM set_config('app.allow_stat_change', 'on', true);  -- 保護トリガー許可
  UPDATE profiles SET gold = gold + v_reward WHERE id = auth.uid();
  UPDATE rank_ratings SET reward_claimed = true, updated_at = now()
    WHERE player_id = auth.uid() AND season = p_season;

  RETURN json_build_object('ok', true, 'rank', v_rank, 'reward', v_reward);
END;
$$;
GRANT EXECUTE ON FUNCTION rank_claim_season_reward(text) TO authenticated;

-- ⑧ [開発用] CDリセット（テスト用・is_admin限定。一般公開後も管理者専用のまま残す）
CREATE OR REPLACE FUNCTION rank_dev_reset_cd()
RETURNS json
LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND is_admin) THEN
    RETURN json_build_object('error', '権限がありません');
  END IF;
  UPDATE rank_ratings SET last_match_at = NULL, pending_opponent = NULL, pending_at = NULL
    WHERE player_id = auth.uid() AND season = rank_current_season();
  RETURN json_build_object('ok', true);
END;
$$;
GRANT EXECUTE ON FUNCTION rank_dev_reset_cd() TO authenticated;
