-- ============================================================
-- 対人戦（PvP）  ※開発者限定の先行実装
-- ------------------------------------------------------------
-- ① pvp_get_skillsets(p_target): 相手の「出撃(sortie)」スキルセットを取得。
--    RLS で他者の skill_sets は読めないため SECURITY DEFINER。呼び出し元が
--    is_admin の場合のみ許可（開発者限定）。
-- ② pvp_results テーブル＋ pvp_record_result(): 勝敗を一時記録（検証用）。
--
-- 適用順の制約は特に無し（他SQLの関数を上書きしない独立追加）。
-- ============================================================

-- ① 相手のPvPスキルセット取得 -------------------------------------------------
--    'pvp' セットにアクティブスキルが1つでもあれば 'pvp' を、無ければ 'sortie'(出撃)を返す。
--    （パッシブのみ/空のPvPセットは「未設定」扱いで出撃に流用＝クライアントloadLoadoutと同方針）
CREATE OR REPLACE FUNCTION pvp_get_skillsets(p_target uuid)
RETURNS json
LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_is_admin boolean;
  v_result   json;
  v_use_type text;
BEGIN
  SELECT COALESCE(is_admin, false) INTO v_is_admin FROM profiles WHERE id = auth.uid();
  IF NOT v_is_admin THEN
    RETURN json_build_object('error', '権限がありません');
  END IF;

  -- PvPセットにアクティブ(非パッシブ)スキルがあれば 'pvp'、無ければ 'sortie'
  SELECT CASE WHEN EXISTS (
      SELECT 1 FROM skill_sets s2
      JOIN skills sk2 ON sk2.id = s2.skill_id
      WHERE s2.player_id = p_target AND s2.set_type = 'pvp'
        AND COALESCE(sk2.type, '') <> 'パッシブ'
    ) THEN 'pvp' ELSE 'sortie' END
  INTO v_use_type;

  SELECT COALESCE(json_agg(t ORDER BY t.slot_order), '[]'::json) INTO v_result
  FROM (
    SELECT ss.id, ss.player_id, ss.skill_id, ss.slot_order,
           COALESCE(ss.use_count, 1) AS use_count, ss.set_type,
           row_to_json(sk) AS skills
    FROM skill_sets ss
    LEFT JOIN skills sk ON sk.id = ss.skill_id
    WHERE ss.player_id = p_target
      AND COALESCE(ss.set_type, 'sortie') = v_use_type
  ) t;

  RETURN json_build_object('ok', true, 'skill_sets', v_result);
END;
$$;
GRANT EXECUTE ON FUNCTION pvp_get_skillsets(uuid) TO authenticated;

-- ② 勝敗の一時記録 ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pvp_results (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  challenger_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  opponent_id   uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  winner        text NOT NULL,           -- 'challenger' | 'opponent' | 'draw'
  turns         int  NOT NULL DEFAULT 0,
  a_hp_pct      real NOT NULL DEFAULT 0, -- 挑戦者の残HP割合
  b_hp_pct      real NOT NULL DEFAULT 0, -- 相手の残HP割合
  created_at    timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE pvp_results ENABLE ROW LEVEL SECURITY;

-- 自分が関与した記録だけ閲覧可
DROP POLICY IF EXISTS pvp_results_select_own ON pvp_results;
CREATE POLICY pvp_results_select_own ON pvp_results
  FOR SELECT USING (auth.uid() = challenger_id OR auth.uid() = opponent_id);

CREATE OR REPLACE FUNCTION pvp_record_result(
  p_opponent uuid,
  p_winner   text,
  p_turns    int,
  p_a_hp_pct real,
  p_b_hp_pct real
) RETURNS json
LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_is_admin boolean;
  v_id       bigint;
BEGIN
  SELECT COALESCE(is_admin, false) INTO v_is_admin FROM profiles WHERE id = auth.uid();
  IF NOT v_is_admin THEN
    RETURN json_build_object('error', '権限がありません');
  END IF;
  IF p_winner NOT IN ('challenger', 'opponent', 'draw') THEN
    RETURN json_build_object('error', 'winner不正');
  END IF;

  INSERT INTO pvp_results(challenger_id, opponent_id, winner, turns, a_hp_pct, b_hp_pct)
  VALUES (auth.uid(), p_opponent, p_winner, COALESCE(p_turns,0), COALESCE(p_a_hp_pct,0), COALESCE(p_b_hp_pct,0))
  RETURNING id INTO v_id;

  RETURN json_build_object('ok', true, 'id', v_id);
END;
$$;
GRANT EXECUTE ON FUNCTION pvp_record_result(uuid, text, int, real, real) TO authenticated;
